name: CI Agda

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Scarica il codice del tuo repository
      - uses: actions/checkout@v4

      # 2. Configura Agda (Usa wenkokke/setup-agda o agda/agda-setup-action)
      - name: Setup Agda
        uses: wenkokke/setup-agda@v2
        with:
          agda-version: 'latest'      # Installa l'ultima versione di Agda
          agda-stdlib-version: 'recommended' # Opzionale: installa la libreria standard

      # 3. Esegui il controllo del tuo file principale
      - name: Check Agda file
        run: PSIU_Protocol.agda
