G <- 0.6180339887
BOX_THRESHOLD <- 0.002
DIAMOND_THRESHOLD <- 0.010
create_hott_type <- function(value, type_label) { structure(list(val = value, type = type_label), class = "HoTT_Type") }
create_path <- function(type_a, type_b, tolerance) { if (type_a$type != type_b$type) return(NULL); distance <- abs(type_a$val - type_b$val); if (distance <= tolerance) return(list(from = type_a, to = type_b, distance = distance, proof = "Reflexivity_Path")) else return(NULL) }
j_rule <- function(path, property_A, property_B) { if (is.null(path)) return("NOISE (Accident)"); if (path$distance <= BOX_THRESHOLD) return(property_A); if (path$distance <= DIAMOND_THRESHOLD) return(property_B) }
#' @export
PsiU_Engine_RL <- function(raw_input_vector) { G_target <- create_hott_type(G, "Gnomonic_Ratio"); prop_A <- "BOX (Necessity) [\u25a1fgno]"; prop_B <- "DIAMOND (Possibility) [\u25c6fgno]"; states <- character(length(raw_input_vector)); offsets <- numeric(length(raw_input_vector)); for (i in 1:length(raw_input_vector)) { current_u <- create_hott_type(raw_input_vector[i], "Gnomonic_Ratio"); path_to_G <- create_path(current_u, G_target, tolerance = DIAMOND_THRESHOLD); states[i] <- j_rule(path_to_G, prop_A, prop_B); offsets[i] <- abs(raw_input_vector[i] - G) }; return(data.frame(Valore_Grezzo = raw_input_vector, Distanza_G = round(offsets, 5), Stato_Modale = states, stringsAsFactors = FALSE)) }
#' @export
PsiU_MultiLibrary_Tree <- function(new_value, user_filename = "user_tableau_library.rds") { if(file.exists(user_filename)) { tree_lib <- readRDS(user_filename) } else { tree_lib <- list(HISTORY = numeric(), BOX_CRYSTAL = numeric(), NOISE_CRYSTAL = numeric(), STEPS = 0) }; tree_lib$STEPS <- tree_lib$STEPS + 1; current_res <- PsiU_Engine_RL(new_value); str_stato <- current_res$Stato_Modale; dist_g <- current_res$Distanza_G; cat(sprintf("[STEP %d] Valore in esame: %.5f | Stato: %s | Distanza G: %.5f\n", tree_lib$STEPS, new_value, str_stato, dist_g)); if(tree_lib$STEPS <= 3) { tree_lib$HISTORY <- c(tree_lib$HISTORY, new_value); saveRDS(tree_lib, user_filename); cat(" -> Fase iniziale (Passi 1-3): Ancoraggio del valore nel flusso storico.\n\n"); return(tree_lib) }; distanze_storiche <- abs(tree_lib$HISTORY - new_value); indice_vicino <- which.min(distanze_storiche); valore_vicino <- tree_lib$HISTORY[indice_vicino]; min_dist <- distanze_storiche[indice_vicino]; cat(sprintf(" -> ANALISI SCOSTAMENTO STORICO: Il valore corrente si avvicina al vecchio valore %.5f (Scostamento: %.5f)\n", valore_vicino, min_dist)); if(str_stato == "DIAMOND (Possibility) [\u25c6fgno]") { cat(" -> ALBERO DI CONFUTAZIONE: Il ramo rimane APERTO [♢]. Fluttuazione nel possibile. Nessuna chiusura logica.\n") } else if(str_stato == "BOX (Necessity) [\u25a1fgno]") { cat(" -> ALBERO DI CONFUTAZIONE: Il ramo si CHIUDE [□] (Necessità)! Salvataggio e cristallizzazione del numero esatto.\n"); tree_lib$BOX_CRYSTAL <- c(tree_lib$BOX_CRYSTAL, new_value) } else { cat(" -> ALBERO DI CONFUTAZIONE: Il ramo si CHIUDE [Accidente] (Noise)! Cristallizzazione del valore asimmetrico.\n"); tree_lib$NOISE_CRYSTAL <- c(tree_lib$NOISE_CRYSTAL, new_value) }; tree_lib$HISTORY <- c(tree_lib$HISTORY, new_value); saveRDS(tree_lib, user_filename); cat("Libreria ad albero aggiornata e salvata.\n\n"); return(tree_lib) }
