name: PSIU_Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Risolve il warning di Node.js

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Run Protocol
        run: |
          # Questo comando cerca OGNI file .R e lo carica finché non trova stress_test
          Rscript -e 'lapply(list.files(pattern = "\\.[rR]$"), source); stress_test(10000)'
