name: PSIU_Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Run Protocol
        run: |
          # Questo comando carica l'unico file .R presente, qualunque sia il nome
          Rscript -e 'source(list.files(pattern = "\\.[rR]$")[1]); stress_test(10000)'
