name: Check PSIU Protocol Well-Typedness

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify-sst:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Agda
        uses: agda/setup-agda@v2
        with:
          agda-version: '2.6.4'

      - name: Verify PSIU_Protocol
        run: |
          # Il comando punta ora correttamente al file PSIU_Protocol.agda
          # -i . serve per risolvere gli import locali del progetto gituv
          # --without-K risolve il problema dei semisimpliciali evitando l'assioma K
          agda --no-libraries -i . --without-K PSIU_Protocol.agda
