name: Check PSIU Protocol Well-Typedness

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify-sst:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Agda
        uses: agda/setup-agda@v2
        with:
          agda-version: '2.6.4' # Versione stabile per SST e CwF

      - name: Verify PSIU_Protocol
        run: |
          # Usiamo -i . per permettere ad Agda di trovare i file locali di gituv
          # Usiamo --without-K perché essenziale per i tipi semisimpliciali
          agda --no-libraries -i . --without-K PSIU_Protocol.agda

